### ISSUE TITLE
use of previous_frame in motion_heatmap section ?

### ISSUE THREAD

**Issue by Chakri-V-V** [intel-iot-devkit/python-cv-samples#4]
I uncommented the previous_frame at all the 3 instances & the code still worked . Can you describe me the use of deep-copying the converted gray frame ?

**Comment by fromgilbert** [comment]
@Chakri-V-V it's an artifact from an early version that I created, I'll remove it.  I was thinking I would need it to do a diff on the previous frame, before I realized I can just use the fgbg background subraction function. Good catch :)
